### ISSUE TITLE
【RSShub】Add register to lib/utils/ofetch error( in index.ts is ok)

### ISSUE THREAD

**Issue by GrinZero** [GrinZero/node-network-devtools#23]
### Describe the bug

I tried to add node-network-devtools to the [rsshub](https://github.com/DIYgod/RSSHub) project for easier debugging, but encountered two problems:
1. The addition was successful on the index.ts page, but the request could not be received.
2. Attempted to add on the lib/tiles/ofetch.ts page, but encountered an error.
This is describing the second issue.

### Steps to reproduce

1. go `lib/utils/ofetch.ts`
2. add code
```ts
import { register } from 'node-network-devtools';
register();
```
3. run `pnpm dev`

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M3
    Memory: 64.66 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    pnpm: 9.12.1 - ~/.nvm/versions/node/v18.20.2/bin/pnpm
    Watchman: 2024.09.09.00 - /opt/homebrew/bin/watchman
  npmPackages:
    node-network-devtools: file:/Users/bugyaluwang/Desktop/my-projects/node-network-devtools/packages/network-debugger => 1.0.12
```

### Logs

<details>
<summary>Click to expand!</summary>

```bash

uncaughtException:  Error: listen EADDRINUSE: address already in use :::5270
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:593:12)
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at new WebSocketServer (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/ws/lib/websocket-server.js:102:20)
    at J.initServer (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:2:2310)
    at new J (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:2:1240)
    at M (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:747)
    at Object.<anonymous> (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:870)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Object.transformer (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/tsx@4.19.1/node_modules/tsx/dist/register-DpmFHar1.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5270
}
uncaughtException:  Error: listen EADDRINUSE: address already in use :::5271
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:593:12)
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at new WebSocketServer (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/ws/lib/websocket-server.js:102:20)
    at new $ (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:1:1015)
    at new J (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:2:971)
    at M (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:747)
    at O (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:979)
    at process.<anonymous> (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:1208)
    at process.emit (node:events:517:28)
    at process.emit (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/tsx@4.19.1/node_modules/tsx/dist/suppress-warnings.cjs:1:472)
    at process._fatalException (node:internal/process/execution:169:25) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5271
}
uncaughtException:  Error: listen EADDRINUSE: address already in use :::5270
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:593:12)
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at new WebSocketServer (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/ws/lib/websocket-server.js:102:20)
    at J.initServer (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:2:2310)
    at new J (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:2:1240)
    at M (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:747)
    at O (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:979)
    at process.<anonymous> (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:1208)
    at process.emit (node:events:517:28)
    at process.emit (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/tsx@4.19.1/node_modules/tsx/dist/suppress-warnings.cjs:1:472)
    at process._fatalException (node:internal/process/execution:169:25) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5270
}
uncaughtException:  Error: listen EADDRINUSE: address already in use :::5271
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_uvExceptionWithHostPort (node:internal/errors:593:12)
    at Server.setupListenHandle [as _listen2] (node:net:1817:16)
    at listenInCluster (node:net:1865:12)
    at Server.listen (node:net:1953:7)
    at new WebSocketServer (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/ws@8.18.0_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/ws/lib/websocket-server.js:102:20)
    at new $ (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:1:1015)
    at new J (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:2:971)
    at M (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:747)
    at O (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:979)
    at process.<anonymous> (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/node-network-devtools@file+..+node-network-devtools+packages+network-debugger_bufferutil@4.0.8_utf-8-validate@5.0.10/node_modules/node-network-devtools/dist/fork.js:4:1208)
    at process.emit (node:events:517:28)
    at process.emit (/Users/bugyaluwang/Desktop/my-projects/RSSHub/node_modules/.pnpm/tsx@4.19.1/node_modules/tsx/dist/suppress-warnings.cjs:1:472)
    at process._fatalException (node:internal/process/execution:169:25) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5271
}
Restart limit reached
```

</details>

**Comment by GrinZero** [comment]
Perhaps `register` is a function with side effects

**Comment by GrinZero** [comment]
link https://github.com/DIYgod/RSSHub/issues/17157

**Comment by GrinZero** [comment]
Close. We did our best.
